In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
print(torch.__version__)

2.4.0


# Introduction to Tensors

## Creating tensors

In [4]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
# Get tensor back as python int
scalar.item()

7

In [20]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [21]:
vector.ndim

1

In [22]:
vector.shape

torch.Size([2])

In [23]:
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [24]:
MATRIX.ndim

2

In [25]:
MATRIX.shape

torch.Size([2, 2])

In [39]:
# Tensor

TENSOR = torch.tensor([
  [
    [1,2,3], [4,5,6], [7,8,9],
  ],
  [
    [1,2,3], [4,5,6], [7,8,9]
  ],
])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [40]:
TENSOR.ndim

3

In [41]:
TENSOR.shape

torch.Size([2, 3, 3])

### Random Tensors

Why Random Tensors?

Important because the way many neuralnetworks (NN) learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look a data -> update random numbers -> look at data -> update random numbers`

In [47]:
# create a random tensor of size (2, 3, 4) -> 3 dimensions
random_tensor = torch.rand(2, 3, 4)
random_tensor

tensor([[[0.7837, 0.1208, 0.5446, 0.9712],
         [0.6336, 0.6946, 0.4717, 0.9421],
         [0.2772, 0.0752, 0.0167, 0.0675]],

        [[0.9347, 0.0450, 0.0747, 0.8811],
         [0.6615, 0.9193, 0.8062, 0.1023],
         [0.1966, 0.5287, 0.4299, 0.9427]]])

In [45]:
random_tensor.ndim

2