In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
print(torch.__version__)

2.4.0


# Introduction to Tensors

## Creating tensors

In [3]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# Get tensor back as python int
scalar.item()

7

In [6]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# Tensor

TENSOR = torch.tensor([
  [
    [1,2,3], [4,5,6], [7,8,9],
  ],
  [
    [1,2,3], [4,5,6], [7,8,9]
  ],
])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([2, 3, 3])

### Random Tensors

Why Random Tensors?

Important because the way many neuralnetworks (NN) learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look a data -> update random numbers -> look at data -> update random numbers`

In [15]:
# create a random tensor of size (2, 3, 4) -> 3 dimensions
random_tensor = torch.rand(2, 3, 4)
random_tensor

tensor([[[0.2996, 0.0841, 0.1549, 0.3343],
         [0.8216, 0.4263, 0.0756, 0.7314],
         [0.7700, 0.7770, 0.1085, 0.4796]],

        [[0.7247, 0.9429, 0.4369, 0.2164],
         [0.6942, 0.6653, 0.0145, 0.3802],
         [0.2143, 0.3795, 0.2367, 0.2401]]])

In [16]:
random_tensor.ndim

3

In [17]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # color, height, width (3, 224, 224)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and Ones

In [18]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
zeros*random_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [20]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [21]:
ones.dtype

torch.float32