In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
print(torch.__version__)

2.4.0


# Introduction to Tensors

## Creating tensors

In [4]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
# Get tensor back as python int
scalar.item()

7

In [20]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [21]:
vector.ndim

1

In [22]:
vector.shape

torch.Size([2])

In [23]:
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [24]:
MATRIX.ndim

2

In [25]:
MATRIX.shape

torch.Size([2, 2])

In [28]:
# Tensor

TENSOR = torch.tensor([
  [
    [1,2,3], [4,5,6], [7,8,9]
    ]
  ]
)
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [29]:
TENSOR.ndim

3

In [30]:
TENSOR.shape

torch.Size([1, 3, 3])